name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git unzip openjdk-21-jdk \
          python3-pip autoconf libtool \
          pkg-config zlib1g-dev libncurses-dev \
          libtinfo6 libssl-dev

    - name: Install Buildozer stack
      run: |
        pip install --upgrade pip wheel
        pip install 
          buildozer==1.6.0 \
          "python-for-android==2024.1.21" \
          cython==3.0.8 \
          virtualenv==20.25.1

    - name: Setup Android SDK
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip commandlinetools-linux-*.zip -d ~/.buildozer/android/platform/android-sdk/cmdline-tools
        mv ~/.buildozer/android/platform/android-sdk/cmdline-tools/cmdline-tools ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest

    - name: Accept licenses
      run: |
        mkdir -p ~/.android/licenses
        echo -e "8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e\n24333f8a63b6825ea9c5514f83c2829b004d1fee\n84831b9409646a918e30573bab4c9c91346d8abd" > ~/.android/licenses/android-sdk-license

    - name: Install Android components
      run: |
        ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager \
          --install \
          "build-tools;34.0.0" \
          "platforms;android-34" \
          "platform-tools" \
          "ndk;25.2.9519653" \
          "cmake;3.22.1" \
          --sdk_root=$HOME/.buildozer/android/platform/android-sdk

    - name: Build APK
      env:
        ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk
        ANDROID_NDK_HOME: /home/runner/.buildozer/android/platform/android-ndk-r25b
      run: |
        buildozer android clean
        buildozer -v android release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: HolaMundoAPK
        path: bin/*-release.apk
        retention-days: 7
